import json
from pocketbase import PocketBase

client = PocketBase('http://127.0.0.1:8090')

with open('mydatav2.json', 'r', encoding="utf-8") as json_file:
    data = json.load(json_file)


viable_tags = ['LYME DISEASE', 'ALL CONDITIONS (ANY)', 'ZINC', 'ALL MEDICATIONS (ANY)', 'MINOCYCLINE', 'ESCITALOPRAM', 'PAROXETINE', 'BARTONELLOSIS', 'AZITHROMYCIN', 'DOXYCYCLINE', 'LEVOTHYROXINE', 'PENICILLIN G', 'VENLAFAXINE', 'ALPRAZOLAM', 'RANITIDINE', 'CLONAZEPAM', 'HYDROXYZINE', 'OMEPRAZOLE', 'FLUOXETINE', 'SERTRALINE', 'ANAPLASMOSIS', 'PANTOPRAZOLE', 'DIAZEPAM', 'DULOXETINE', 'ACETAMINOPHEN', 'PREGABALIN', 'ROCKY MOUNTAIN SPOTTED FEVER', 'CITALOPRAM', 'TINIDAZOLE', 'TOPIRAMATE', 'LORAZEPAM', 'EHRLICHIOSIS', 'LIOTHYRONINE', 'CETIRIZINE', 'LEVOFLOXACIN', 'METHYLPHENIDATE', 'CEFTRIAXONE', 'BABESIOSIS', 'CHOLESTYRAMINE', 'METRONIDAZOLE', 'AMOXICILLIN', 'TULAREMIA', 'TETRACYCLINE', 'CIPROFLOXACIN', 'ONDANSETRON', 'CYCLOBENZAPRINE', 'HYDROCORTISONE', 'FLUCONAZOLE', 'CEPHALEXIN', 'DEXAMETHASONE', 'PROMETHAZINE', 'DICYCLOMINE', 'CLARITHROMYCIN', 'NAPROXEN', 'DIPHENHYDRAMINE', 'ACETAZOLAMIDE', 'MELOXICAM', 'CEFUROXIME', 'NORTRIPTYLINE', 'AMITRIPTYLINE', 'MECLIZINE', 'OXYCODONE', 'CLINDAMYCIN', 'HYDROCODONE', 'TRAZODONE', 'FENTANYL', 'METHYLPREDNISOLONE', 'ESOMEPRAZOLE', 'NALTREXONE', 'CELECOXIB', 'NIACIN', 'BOTULINUM TOXIN TYPE A', 'RIFAMPIN', 'VALACICLOVIR', 'HYDROXYCHLOROQUINE', 'ARIPIPRAZOLE', 'FLUVOXAMINE', 'RIFAXIMIN', 'MIRTAZAPINE', 'METHOTREXATE', 'CROMOGLICIC ACID', 'VANCOMYCIN', 'COLCHICINE', 'ACYCLOVIR', 'DISULFIRAM', 'NYSTATIN', 'L-TRYPTOPHAN', 'DAPTOMYCIN', 'AZLOCILLIN']

i = 0
for dictionary in data:
    # guarantee the tags are uppercase
    dictionary["tags"] = [term.upper() for term in dictionary["tags"]]

    body = dictionary["body"].lower()
    tags = dictionary["tags"]
    if all(item in viable_tags for item in tags):
        result = client.collection("posts").create(dictionary)

    i += 1
    if (i % 100 == 0):
        print(i)